### ISSUE TITLE
Update Lab #1

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/cmsc22000#8]
Lab #1 needs to be updated for 2019 (I have created a `2019/lab1` branch for this) 

Besides reviewing it (and making sure the examples still work), the following clarifications were posted on Piazza (and need to be addressed):

> When you push for the first time, you may get a message saying that "push.default is unset", and suggesting two possible commands to remedy the situation. While the rest of the lab will work fine if you don't run either of these commands, you should run the command to use "simple" (this will prevent the warning from appearing every time you push)
> 
> When you run "git clone", take into account that the repository is not cloned into the current directory. A new directory (with the same name as the repository) will be created in the current directory, and you will need to cd into it to use Git commands for that repository.
> 
> In Task 9, you should ignore any Git instructions provided in the fzf documentation (specially in the README file). These will lead you down the wrong path.

**Comment by borjasotomayor** [comment]
@mpcsh, @lydiafilipe: I've made a pass through the lab and made a few additions and minor corrections. I've verified that Task 9 and Task 13 (the ones involving other GitHub repos not under our control) still work fine. Please make a pass through the lab; at least one of you should re-run the commands on a CSIL machine to make sure there's no surprises anywhere.

**Comment by mpcsh** [comment]
Oh dang you didn't have to do that - I had it on my todo list for tomorrow morning. My bad for not communicating that. I'll run through it when I wake up.

**Comment by mpcsh** [comment]
Alright, I ran through it and everything looks good. I also pushed a change to introduce them to `git diff`, which I inexplicably left out last year.

Also @borjasotomayor - at least on my laptop, `hugo` refuses to build, complaining about a missing `head` partial. Does it work for you?

**Comment by mpcsh** [comment]
Also, the branch was named `2019/lab` - I renamed it to `2019/lab1`. Y'all may have to `git remote prune origin` and re-checkout.

**Comment by borjasotomayor** [comment]
Yeah, Hugo (latest version) builds the website fine on my end.

**Comment by lydiafilipe** [comment]
Just did a read-through and looks good to me. The only thing we might want to add is how to exit vim after we mention it as the default editor on the csil machines, though that isn't too crucial

**Comment by borjasotomayor** [comment]
Cool, I just published the lab to the website (including Lydia's suggested vim comment)
